[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#e5e5e7"
font = "sans serif"
